blank_issues_enabled: false
contact_links:
  - name: Support securite CESIZEN
    url: https://github.com/lypouchh/CESIZEN/security/advisories
    about: Utiliser ce canal pour tout signalement de faille de securite.
