#!/usr/bin/env bash

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BACKEND_DIR="$REPO_ROOT/backend"
ARTIFACT_DIR="$BACKEND_DIR/artifacts"
SQLITE_DB="$BACKEND_DIR/database/ci-migrations.sqlite"
OUTPUT_FILE="$ARTIFACT_DIR/migration.sql"

cd "$BACKEND_DIR"

mkdir -p "$ARTIFACT_DIR"
rm -f "$SQLITE_DB" "$OUTPUT_FILE"
touch "$SQLITE_DB"

export DB_CONNECTION=sqlite
export DB_DATABASE="$SQLITE_DB"

{
  echo "-- Generated by CI from Laravel migrations"
  echo "-- This script is an artifact for review and traceability"
  echo "-- It is generated in CI and must not be auto-applied in CD"
  echo
  php artisan migrate --database=sqlite --pretend --no-interaction
} > "$OUTPUT_FILE"

if [[ ! -s "$OUTPUT_FILE" ]]; then
  echo "Migration SQL artifact is empty" >&2
  exit 1
fi

echo "Generated migration artifact: $OUTPUT_FILE"