#!/usr/bin/env bash

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BACKEND_DIR="$REPO_ROOT/backend"
ARTIFACT_DIR="$BACKEND_DIR/artifacts"
OUTPUT_FILE="$ARTIFACT_DIR/migration.sql"
RUNNER_TMP_DIR="${RUNNER_TEMP:-/tmp}"
SQLITE_DB="$(mktemp "$RUNNER_TMP_DIR/ci-migrations-XXXXXX.sqlite")"
RAW_OUTPUT_FILE="$(mktemp "$RUNNER_TMP_DIR/ci-migration-output-XXXXXX.log")"

cd "$BACKEND_DIR"

mkdir -p "$ARTIFACT_DIR"
rm -f "$OUTPUT_FILE"

cleanup() {
  rm -f "$SQLITE_DB" "$RAW_OUTPUT_FILE"
}
trap cleanup EXIT

export DB_CONNECTION=sqlite
export DB_DATABASE="$SQLITE_DB"

if ! php artisan migrate --database=sqlite --pretend --no-interaction > "$RAW_OUTPUT_FILE" 2>&1; then
  echo "Failed to generate migration SQL artifact." >&2
  cat "$RAW_OUTPUT_FILE" >&2
  exit 1
fi

{
  echo "-- Generated by CI from Laravel migrations"
  echo "-- This script is an artifact for review and traceability"
  echo "-- It is generated in CI and must not be auto-applied in CD"
  echo
  cat "$RAW_OUTPUT_FILE"
} > "$OUTPUT_FILE"

if [[ ! -s "$OUTPUT_FILE" ]]; then
  echo "Migration SQL artifact is empty" >&2
  exit 1
fi

echo "Generated migration artifact: $OUTPUT_FILE"